apiVersion: apps/v1
kind: Deployment
metadata:
  name: roulette-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roulette-service
  template:
    metadata:
      labels:
        app: roulette-service
    spec:
      containers:
        - name: roulette-service
          image: jfcasinoacr1.azurecr.io/roulette-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          env:
          - name: WALLET_SERVICE_URL
            value: http://wallet-service:8080
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: roulette-db-secret
                key: SPRING_DATASOURCE_URL

          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: roulette-db-secret
                key: SPRING_DATASOURCE_USERNAME

          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: roulette-db-secret
                key: SPRING_DATASOURCE_PASSWORD

          - name: SPRING_JPA_DATABASE_PLATFORM
            valueFrom:
              secretKeyRef:
                name: roulette-db-secret
                key: SPRING_JPA_DATABASE_PLATFORM
          
          - name: EVENT_HUB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: eventhub-secret
                key: EVENT_HUB_CONNECTION_STRING

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
