apiVersion: v1
kind: Service
metadata:
  name: roulette-service
spec:
  type: ClusterIP
  selector:
    app: roulette-service
  ports:
    - port: 8080          # Service accessible port
      targetPort: 8080    # Forward to container port 8080
      protocol: TCP
