apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jfcasino-ingress
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - http:
        paths:
          - path: /wallets
            pathType: Prefix
            backend:
              service:
                name: wallet-service
                port:
                  number: 8080
          - path: /stats
            pathType: Prefix
            backend:
              service:
                name: stats-service
                port:
                  number: 8080
          - path: /roulette
            pathType: Prefix
            backend:
              service:
                name: roulette-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
              
