spring:
  application:
    name: roulette-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rouletteDB}
    username: ${DB_USERNAME:jf76272}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}  # updated for Docker
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

wallet:
  service:
    url: ${WALLET_SERVICE_URL:http://wallet-service:8080}  # added for Feign

server:
  port: ${SERVER_PORT:8080}
  address: 0.0.0.0